swagger: "2.0"
info:
  version: 1.0.0
  title: MyBank Buyer List - Rest Service
  contact:
    name: MyBank
    url: https://mybankrs.docs.apiary.io
  description: >
    Documentation of the MyBank Buyer List rest service.
host: localhost
basePath: "/mybank-gateway-api/rest/sct01/rs"
schemes:
  - https
paths:
  "/getPayerPSPsSCT01":
    post:
      operationId: getPayerPSPsSCT01
      description: This request allows you to retrieve the list of reachable Buyer Banks in MyBank
      consumes: 
        - string
      parameters:
        - in: header
          name: X-Signature-Type
          type: string
          required: true
        - in: header
          name: X-Signature
          type: string
          format: base64
          required: true
        - in: header
          name: X-Thumbprint
          type: string
          format: base64
          required: true
        - in: body
          name: input
          schema:
            $ref: "#/definitions/getPayerPSPsSCT01Request"
      responses:
        "200":
          description: BuyerList retrieved
          schema:
            $ref: "#/definitions/getPayerPSPsSCT01Response"
        "403":
          description: Forbidden
        "500":
          description: generic error           
definitions:
    getPayerPSPsSCT01Request:
      type: string
    getPayerPSPsSCT01Response:
      type: object
      required:
          - output
      properties:
        output:
          type: object
          properties:
            result:
              type: string
            messages:
              type: array
              items:
                type: object
                properties:
                  code:
                    type: string
                  message:
                    type: string
                  severity:
                    type: string
            body:
              type: object
              properties:
                aliases:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: integer
                      participantID:
                        type: string
                      country:
                        type: string
                      alias:
                        type: string
                      language:
                        type: string
                    

